site_name: monasca-agent
repo_url: https://github.com/openstack/monasca-agent
docs_dir: docs
copyright: (C) Copyright 2015 Hewlett Packard Enterprise Development Company LP

pages:
- [index.md, Home]
- [Agent.md, Agent]
- [Customizations.md, Customizations]
- [MonascaMetrics.md, Monasca Metrics]
- [Plugins.md, Plugins]
